version: '3.8'
services:
  php:
    # image: php:8.3-fpm
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './:/var/www/html'
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - './:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'  # Here also php is connected to nginx
    depends_on:
      - php

  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./data-local/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
